FROM golang:1.25-alpine AS builder
WORKDIR /dex
COPY . .
RUN go build -o dex-binary ./cmd/dex

FROM alpine:latest
RUN apk --no-cache add ca-certificates
COPY --from=builder /dex/dex-binary /usr/local/bin/dex
EXPOSE 5556
ENTRYPOINT ["/usr/local/bin/dex"]
